# Generated by Django 4.1.13 on 2025-07-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_accountmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmapping',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop_api.accountmapping'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='sum_of',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
