# Generated by Django 4.1.13 on 2025-09-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_shopifystore'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
