# Generated by Django 4.1.13 on 2025-09-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0005_shopifystore_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifystore',
            name='store_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
