# Generated by Django 4.1.13 on 2025-09-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0006_alter_shopifystore_store_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceNameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
