# Generated by Django 4.1.13 on 2025-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0007_sourcenamemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcenamemapping',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='sourcenamemapping',
            table='source_mappings',
        ),
    ]
